// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LunchesColumns holds the columns for the "lunches" table.
	LunchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "payer", Type: field.TypeString},
		{Name: "restaurant_name", Type: field.TypeString},
		{Name: "cafe_name", Type: field.TypeString},
		{Name: "payment_time", Type: field.TypeTime},
	}
	// LunchesTable holds the schema information for the "lunches" table.
	LunchesTable = &schema.Table{
		Name:       "lunches",
		Columns:    LunchesColumns,
		PrimaryKey: []*schema.Column{LunchesColumns[0]},
	}
	// LunchParticipantsColumns holds the columns for the "lunch_participants" table.
	LunchParticipantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "payment_id", Type: field.TypeInt, Nullable: true},
	}
	// LunchParticipantsTable holds the schema information for the "lunch_participants" table.
	LunchParticipantsTable = &schema.Table{
		Name:       "lunch_participants",
		Columns:    LunchParticipantsColumns,
		PrimaryKey: []*schema.Column{LunchParticipantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "lunch_participants_lunches_participant",
				Columns:    []*schema.Column{LunchParticipantsColumns[4]},
				RefColumns: []*schema.Column{LunchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LunchesTable,
		LunchParticipantsTable,
	}
)

func init() {
	LunchParticipantsTable.ForeignKeys[0].RefTable = LunchesTable
}
