// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bc-labs-lunch-bot/ent/lunch"
	"bc-labs-lunch-bot/ent/lunchparticipant"
	"bc-labs-lunch-bot/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LunchQuery is the builder for querying Lunch entities.
type LunchQuery struct {
	config
	ctx             *QueryContext
	order           []OrderFunc
	inters          []Interceptor
	predicates      []predicate.Lunch
	withParticipant *LunchParticipantQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LunchQuery builder.
func (lq *LunchQuery) Where(ps ...predicate.Lunch) *LunchQuery {
	lq.predicates = append(lq.predicates, ps...)
	return lq
}

// Limit the number of records to be returned by this query.
func (lq *LunchQuery) Limit(limit int) *LunchQuery {
	lq.ctx.Limit = &limit
	return lq
}

// Offset to start from.
func (lq *LunchQuery) Offset(offset int) *LunchQuery {
	lq.ctx.Offset = &offset
	return lq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lq *LunchQuery) Unique(unique bool) *LunchQuery {
	lq.ctx.Unique = &unique
	return lq
}

// Order specifies how the records should be ordered.
func (lq *LunchQuery) Order(o ...OrderFunc) *LunchQuery {
	lq.order = append(lq.order, o...)
	return lq
}

// QueryParticipant chains the current query on the "participant" edge.
func (lq *LunchQuery) QueryParticipant() *LunchParticipantQuery {
	query := (&LunchParticipantClient{config: lq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lunch.Table, lunch.FieldID, selector),
			sqlgraph.To(lunchparticipant.Table, lunchparticipant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, lunch.ParticipantTable, lunch.ParticipantColumn),
		)
		fromU = sqlgraph.SetNeighbors(lq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Lunch entity from the query.
// Returns a *NotFoundError when no Lunch was found.
func (lq *LunchQuery) First(ctx context.Context) (*Lunch, error) {
	nodes, err := lq.Limit(1).All(setContextOp(ctx, lq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lunch.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lq *LunchQuery) FirstX(ctx context.Context) *Lunch {
	node, err := lq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Lunch ID from the query.
// Returns a *NotFoundError when no Lunch ID was found.
func (lq *LunchQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(1).IDs(setContextOp(ctx, lq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lunch.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lq *LunchQuery) FirstIDX(ctx context.Context) int {
	id, err := lq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Lunch entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Lunch entity is found.
// Returns a *NotFoundError when no Lunch entities are found.
func (lq *LunchQuery) Only(ctx context.Context) (*Lunch, error) {
	nodes, err := lq.Limit(2).All(setContextOp(ctx, lq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lunch.Label}
	default:
		return nil, &NotSingularError{lunch.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lq *LunchQuery) OnlyX(ctx context.Context) *Lunch {
	node, err := lq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Lunch ID in the query.
// Returns a *NotSingularError when more than one Lunch ID is found.
// Returns a *NotFoundError when no entities are found.
func (lq *LunchQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lq.Limit(2).IDs(setContextOp(ctx, lq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lunch.Label}
	default:
		err = &NotSingularError{lunch.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lq *LunchQuery) OnlyIDX(ctx context.Context) int {
	id, err := lq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Lunches.
func (lq *LunchQuery) All(ctx context.Context) ([]*Lunch, error) {
	ctx = setContextOp(ctx, lq.ctx, "All")
	if err := lq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Lunch, *LunchQuery]()
	return withInterceptors[[]*Lunch](ctx, lq, qr, lq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lq *LunchQuery) AllX(ctx context.Context) []*Lunch {
	nodes, err := lq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Lunch IDs.
func (lq *LunchQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, lq.ctx, "IDs")
	if err := lq.Select(lunch.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lq *LunchQuery) IDsX(ctx context.Context) []int {
	ids, err := lq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lq *LunchQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lq.ctx, "Count")
	if err := lq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lq, querierCount[*LunchQuery](), lq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lq *LunchQuery) CountX(ctx context.Context) int {
	count, err := lq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lq *LunchQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lq.ctx, "Exist")
	switch _, err := lq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lq *LunchQuery) ExistX(ctx context.Context) bool {
	exist, err := lq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LunchQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lq *LunchQuery) Clone() *LunchQuery {
	if lq == nil {
		return nil
	}
	return &LunchQuery{
		config:          lq.config,
		ctx:             lq.ctx.Clone(),
		order:           append([]OrderFunc{}, lq.order...),
		inters:          append([]Interceptor{}, lq.inters...),
		predicates:      append([]predicate.Lunch{}, lq.predicates...),
		withParticipant: lq.withParticipant.Clone(),
		// clone intermediate query.
		sql:  lq.sql.Clone(),
		path: lq.path,
	}
}

// WithParticipant tells the query-builder to eager-load the nodes that are connected to
// the "participant" edge. The optional arguments are used to configure the query builder of the edge.
func (lq *LunchQuery) WithParticipant(opts ...func(*LunchParticipantQuery)) *LunchQuery {
	query := (&LunchParticipantClient{config: lq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lq.withParticipant = query
	return lq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Lunch.Query().
//		GroupBy(lunch.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lq *LunchQuery) GroupBy(field string, fields ...string) *LunchGroupBy {
	lq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LunchGroupBy{build: lq}
	grbuild.flds = &lq.ctx.Fields
	grbuild.label = lunch.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Lunch.Query().
//		Select(lunch.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (lq *LunchQuery) Select(fields ...string) *LunchSelect {
	lq.ctx.Fields = append(lq.ctx.Fields, fields...)
	sbuild := &LunchSelect{LunchQuery: lq}
	sbuild.label = lunch.Label
	sbuild.flds, sbuild.scan = &lq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LunchSelect configured with the given aggregations.
func (lq *LunchQuery) Aggregate(fns ...AggregateFunc) *LunchSelect {
	return lq.Select().Aggregate(fns...)
}

func (lq *LunchQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lq); err != nil {
				return err
			}
		}
	}
	for _, f := range lq.ctx.Fields {
		if !lunch.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lq.path != nil {
		prev, err := lq.path(ctx)
		if err != nil {
			return err
		}
		lq.sql = prev
	}
	return nil
}

func (lq *LunchQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Lunch, error) {
	var (
		nodes       = []*Lunch{}
		_spec       = lq.querySpec()
		loadedTypes = [1]bool{
			lq.withParticipant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Lunch).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Lunch{config: lq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lq.withParticipant; query != nil {
		if err := lq.loadParticipant(ctx, query, nodes,
			func(n *Lunch) { n.Edges.Participant = []*LunchParticipant{} },
			func(n *Lunch, e *LunchParticipant) { n.Edges.Participant = append(n.Edges.Participant, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lq *LunchQuery) loadParticipant(ctx context.Context, query *LunchParticipantQuery, nodes []*Lunch, init func(*Lunch), assign func(*Lunch, *LunchParticipant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Lunch)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.LunchParticipant(func(s *sql.Selector) {
		s.Where(sql.InValues(lunch.ParticipantColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PaymentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "payment_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (lq *LunchQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lq.querySpec()
	_spec.Node.Columns = lq.ctx.Fields
	if len(lq.ctx.Fields) > 0 {
		_spec.Unique = lq.ctx.Unique != nil && *lq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lq.driver, _spec)
}

func (lq *LunchQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lunch.Table,
			Columns: lunch.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lunch.FieldID,
			},
		},
		From:   lq.sql,
		Unique: true,
	}
	if unique := lq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lunch.FieldID)
		for i := range fields {
			if fields[i] != lunch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lq *LunchQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lq.driver.Dialect())
	t1 := builder.Table(lunch.Table)
	columns := lq.ctx.Fields
	if len(columns) == 0 {
		columns = lunch.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lq.sql != nil {
		selector = lq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lq.ctx.Unique != nil && *lq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lq.predicates {
		p(selector)
	}
	for _, p := range lq.order {
		p(selector)
	}
	if offset := lq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LunchGroupBy is the group-by builder for Lunch entities.
type LunchGroupBy struct {
	selector
	build *LunchQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lgb *LunchGroupBy) Aggregate(fns ...AggregateFunc) *LunchGroupBy {
	lgb.fns = append(lgb.fns, fns...)
	return lgb
}

// Scan applies the selector query and scans the result into the given value.
func (lgb *LunchGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lgb.build.ctx, "GroupBy")
	if err := lgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LunchQuery, *LunchGroupBy](ctx, lgb.build, lgb, lgb.build.inters, v)
}

func (lgb *LunchGroupBy) sqlScan(ctx context.Context, root *LunchQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lgb.fns))
	for _, fn := range lgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lgb.flds)+len(lgb.fns))
		for _, f := range *lgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LunchSelect is the builder for selecting fields of Lunch entities.
type LunchSelect struct {
	*LunchQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ls *LunchSelect) Aggregate(fns ...AggregateFunc) *LunchSelect {
	ls.fns = append(ls.fns, fns...)
	return ls
}

// Scan applies the selector query and scans the result into the given value.
func (ls *LunchSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ls.ctx, "Select")
	if err := ls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LunchQuery, *LunchSelect](ctx, ls.LunchQuery, ls, ls.inters, v)
}

func (ls *LunchSelect) sqlScan(ctx context.Context, root *LunchQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ls.fns))
	for _, fn := range ls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
