// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bc-labs-lunch-bot/ent/lunchparticipant"
	"bc-labs-lunch-bot/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LunchParticipantDelete is the builder for deleting a LunchParticipant entity.
type LunchParticipantDelete struct {
	config
	hooks    []Hook
	mutation *LunchParticipantMutation
}

// Where appends a list predicates to the LunchParticipantDelete builder.
func (lpd *LunchParticipantDelete) Where(ps ...predicate.LunchParticipant) *LunchParticipantDelete {
	lpd.mutation.Where(ps...)
	return lpd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lpd *LunchParticipantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, LunchParticipantMutation](ctx, lpd.sqlExec, lpd.mutation, lpd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lpd *LunchParticipantDelete) ExecX(ctx context.Context) int {
	n, err := lpd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lpd *LunchParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: lunchparticipant.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lunchparticipant.FieldID,
			},
		},
	}
	if ps := lpd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lpd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lpd.mutation.done = true
	return affected, err
}

// LunchParticipantDeleteOne is the builder for deleting a single LunchParticipant entity.
type LunchParticipantDeleteOne struct {
	lpd *LunchParticipantDelete
}

// Exec executes the deletion query.
func (lpdo *LunchParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := lpdo.lpd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{lunchparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lpdo *LunchParticipantDeleteOne) ExecX(ctx context.Context) {
	lpdo.lpd.ExecX(ctx)
}
