// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bc-labs-lunch-bot/ent/lunch"
	"bc-labs-lunch-bot/ent/lunchparticipant"
	"bc-labs-lunch-bot/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LunchParticipantQuery is the builder for querying LunchParticipant entities.
type LunchParticipantQuery struct {
	config
	ctx         *QueryContext
	order       []OrderFunc
	inters      []Interceptor
	predicates  []predicate.LunchParticipant
	withPayment *LunchQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LunchParticipantQuery builder.
func (lpq *LunchParticipantQuery) Where(ps ...predicate.LunchParticipant) *LunchParticipantQuery {
	lpq.predicates = append(lpq.predicates, ps...)
	return lpq
}

// Limit the number of records to be returned by this query.
func (lpq *LunchParticipantQuery) Limit(limit int) *LunchParticipantQuery {
	lpq.ctx.Limit = &limit
	return lpq
}

// Offset to start from.
func (lpq *LunchParticipantQuery) Offset(offset int) *LunchParticipantQuery {
	lpq.ctx.Offset = &offset
	return lpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lpq *LunchParticipantQuery) Unique(unique bool) *LunchParticipantQuery {
	lpq.ctx.Unique = &unique
	return lpq
}

// Order specifies how the records should be ordered.
func (lpq *LunchParticipantQuery) Order(o ...OrderFunc) *LunchParticipantQuery {
	lpq.order = append(lpq.order, o...)
	return lpq
}

// QueryPayment chains the current query on the "payment" edge.
func (lpq *LunchParticipantQuery) QueryPayment() *LunchQuery {
	query := (&LunchClient{config: lpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := lpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := lpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(lunchparticipant.Table, lunchparticipant.FieldID, selector),
			sqlgraph.To(lunch.Table, lunch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, lunchparticipant.PaymentTable, lunchparticipant.PaymentColumn),
		)
		fromU = sqlgraph.SetNeighbors(lpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LunchParticipant entity from the query.
// Returns a *NotFoundError when no LunchParticipant was found.
func (lpq *LunchParticipantQuery) First(ctx context.Context) (*LunchParticipant, error) {
	nodes, err := lpq.Limit(1).All(setContextOp(ctx, lpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lunchparticipant.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lpq *LunchParticipantQuery) FirstX(ctx context.Context) *LunchParticipant {
	node, err := lpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LunchParticipant ID from the query.
// Returns a *NotFoundError when no LunchParticipant ID was found.
func (lpq *LunchParticipantQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lpq.Limit(1).IDs(setContextOp(ctx, lpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lunchparticipant.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lpq *LunchParticipantQuery) FirstIDX(ctx context.Context) int {
	id, err := lpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LunchParticipant entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LunchParticipant entity is found.
// Returns a *NotFoundError when no LunchParticipant entities are found.
func (lpq *LunchParticipantQuery) Only(ctx context.Context) (*LunchParticipant, error) {
	nodes, err := lpq.Limit(2).All(setContextOp(ctx, lpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lunchparticipant.Label}
	default:
		return nil, &NotSingularError{lunchparticipant.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lpq *LunchParticipantQuery) OnlyX(ctx context.Context) *LunchParticipant {
	node, err := lpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LunchParticipant ID in the query.
// Returns a *NotSingularError when more than one LunchParticipant ID is found.
// Returns a *NotFoundError when no entities are found.
func (lpq *LunchParticipantQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = lpq.Limit(2).IDs(setContextOp(ctx, lpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lunchparticipant.Label}
	default:
		err = &NotSingularError{lunchparticipant.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lpq *LunchParticipantQuery) OnlyIDX(ctx context.Context) int {
	id, err := lpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LunchParticipants.
func (lpq *LunchParticipantQuery) All(ctx context.Context) ([]*LunchParticipant, error) {
	ctx = setContextOp(ctx, lpq.ctx, "All")
	if err := lpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LunchParticipant, *LunchParticipantQuery]()
	return withInterceptors[[]*LunchParticipant](ctx, lpq, qr, lpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (lpq *LunchParticipantQuery) AllX(ctx context.Context) []*LunchParticipant {
	nodes, err := lpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LunchParticipant IDs.
func (lpq *LunchParticipantQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, lpq.ctx, "IDs")
	if err := lpq.Select(lunchparticipant.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lpq *LunchParticipantQuery) IDsX(ctx context.Context) []int {
	ids, err := lpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lpq *LunchParticipantQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Count")
	if err := lpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, lpq, querierCount[*LunchParticipantQuery](), lpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (lpq *LunchParticipantQuery) CountX(ctx context.Context) int {
	count, err := lpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lpq *LunchParticipantQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, lpq.ctx, "Exist")
	switch _, err := lpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (lpq *LunchParticipantQuery) ExistX(ctx context.Context) bool {
	exist, err := lpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LunchParticipantQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lpq *LunchParticipantQuery) Clone() *LunchParticipantQuery {
	if lpq == nil {
		return nil
	}
	return &LunchParticipantQuery{
		config:      lpq.config,
		ctx:         lpq.ctx.Clone(),
		order:       append([]OrderFunc{}, lpq.order...),
		inters:      append([]Interceptor{}, lpq.inters...),
		predicates:  append([]predicate.LunchParticipant{}, lpq.predicates...),
		withPayment: lpq.withPayment.Clone(),
		// clone intermediate query.
		sql:  lpq.sql.Clone(),
		path: lpq.path,
	}
}

// WithPayment tells the query-builder to eager-load the nodes that are connected to
// the "payment" edge. The optional arguments are used to configure the query builder of the edge.
func (lpq *LunchParticipantQuery) WithPayment(opts ...func(*LunchQuery)) *LunchParticipantQuery {
	query := (&LunchClient{config: lpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	lpq.withPayment = query
	return lpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LunchParticipant.Query().
//		GroupBy(lunchparticipant.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lpq *LunchParticipantQuery) GroupBy(field string, fields ...string) *LunchParticipantGroupBy {
	lpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LunchParticipantGroupBy{build: lpq}
	grbuild.flds = &lpq.ctx.Fields
	grbuild.label = lunchparticipant.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LunchParticipant.Query().
//		Select(lunchparticipant.FieldName).
//		Scan(ctx, &v)
//
func (lpq *LunchParticipantQuery) Select(fields ...string) *LunchParticipantSelect {
	lpq.ctx.Fields = append(lpq.ctx.Fields, fields...)
	sbuild := &LunchParticipantSelect{LunchParticipantQuery: lpq}
	sbuild.label = lunchparticipant.Label
	sbuild.flds, sbuild.scan = &lpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LunchParticipantSelect configured with the given aggregations.
func (lpq *LunchParticipantQuery) Aggregate(fns ...AggregateFunc) *LunchParticipantSelect {
	return lpq.Select().Aggregate(fns...)
}

func (lpq *LunchParticipantQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range lpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, lpq); err != nil {
				return err
			}
		}
	}
	for _, f := range lpq.ctx.Fields {
		if !lunchparticipant.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lpq.path != nil {
		prev, err := lpq.path(ctx)
		if err != nil {
			return err
		}
		lpq.sql = prev
	}
	return nil
}

func (lpq *LunchParticipantQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LunchParticipant, error) {
	var (
		nodes       = []*LunchParticipant{}
		_spec       = lpq.querySpec()
		loadedTypes = [1]bool{
			lpq.withPayment != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LunchParticipant).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LunchParticipant{config: lpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, lpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := lpq.withPayment; query != nil {
		if err := lpq.loadPayment(ctx, query, nodes, nil,
			func(n *LunchParticipant, e *Lunch) { n.Edges.Payment = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (lpq *LunchParticipantQuery) loadPayment(ctx context.Context, query *LunchQuery, nodes []*LunchParticipant, init func(*LunchParticipant), assign func(*LunchParticipant, *Lunch)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LunchParticipant)
	for i := range nodes {
		fk := nodes[i].PaymentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(lunch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "payment_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (lpq *LunchParticipantQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lpq.querySpec()
	_spec.Node.Columns = lpq.ctx.Fields
	if len(lpq.ctx.Fields) > 0 {
		_spec.Unique = lpq.ctx.Unique != nil && *lpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, lpq.driver, _spec)
}

func (lpq *LunchParticipantQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lunchparticipant.Table,
			Columns: lunchparticipant.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lunchparticipant.FieldID,
			},
		},
		From:   lpq.sql,
		Unique: true,
	}
	if unique := lpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lunchparticipant.FieldID)
		for i := range fields {
			if fields[i] != lunchparticipant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lpq *LunchParticipantQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lpq.driver.Dialect())
	t1 := builder.Table(lunchparticipant.Table)
	columns := lpq.ctx.Fields
	if len(columns) == 0 {
		columns = lunchparticipant.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lpq.sql != nil {
		selector = lpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lpq.ctx.Unique != nil && *lpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range lpq.predicates {
		p(selector)
	}
	for _, p := range lpq.order {
		p(selector)
	}
	if offset := lpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LunchParticipantGroupBy is the group-by builder for LunchParticipant entities.
type LunchParticipantGroupBy struct {
	selector
	build *LunchParticipantQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lpgb *LunchParticipantGroupBy) Aggregate(fns ...AggregateFunc) *LunchParticipantGroupBy {
	lpgb.fns = append(lpgb.fns, fns...)
	return lpgb
}

// Scan applies the selector query and scans the result into the given value.
func (lpgb *LunchParticipantGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lpgb.build.ctx, "GroupBy")
	if err := lpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LunchParticipantQuery, *LunchParticipantGroupBy](ctx, lpgb.build, lpgb, lpgb.build.inters, v)
}

func (lpgb *LunchParticipantGroupBy) sqlScan(ctx context.Context, root *LunchParticipantQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(lpgb.fns))
	for _, fn := range lpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*lpgb.flds)+len(lpgb.fns))
		for _, f := range *lpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*lpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LunchParticipantSelect is the builder for selecting fields of LunchParticipant entities.
type LunchParticipantSelect struct {
	*LunchParticipantQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lps *LunchParticipantSelect) Aggregate(fns ...AggregateFunc) *LunchParticipantSelect {
	lps.fns = append(lps.fns, fns...)
	return lps
}

// Scan applies the selector query and scans the result into the given value.
func (lps *LunchParticipantSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lps.ctx, "Select")
	if err := lps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LunchParticipantQuery, *LunchParticipantSelect](ctx, lps.LunchParticipantQuery, lps, lps.inters, v)
}

func (lps *LunchParticipantSelect) sqlScan(ctx context.Context, root *LunchParticipantQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lps.fns))
	for _, fn := range lps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
