// Code generated by ent, DO NOT EDIT.

package ent

import (
	"bc-labs-lunch-bot/ent/lunch"
	"bc-labs-lunch-bot/ent/lunchparticipant"
	"bc-labs-lunch-bot/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	lunchFields := schema.Lunch{}.Fields()
	_ = lunchFields
	// lunchDescCreatedAt is the schema descriptor for created_at field.
	lunchDescCreatedAt := lunchFields[0].Descriptor()
	// lunch.DefaultCreatedAt holds the default value on creation for the created_at field.
	lunch.DefaultCreatedAt = lunchDescCreatedAt.Default.(func() time.Time)
	// lunchDescUpdatedAt is the schema descriptor for updated_at field.
	lunchDescUpdatedAt := lunchFields[1].Descriptor()
	// lunch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lunch.DefaultUpdatedAt = lunchDescUpdatedAt.Default.(func() time.Time)
	lunchparticipantFields := schema.LunchParticipant{}.Fields()
	_ = lunchparticipantFields
	// lunchparticipantDescCreatedAt is the schema descriptor for created_at field.
	lunchparticipantDescCreatedAt := lunchparticipantFields[1].Descriptor()
	// lunchparticipant.DefaultCreatedAt holds the default value on creation for the created_at field.
	lunchparticipant.DefaultCreatedAt = lunchparticipantDescCreatedAt.Default.(func() time.Time)
	// lunchparticipantDescUpdatedAt is the schema descriptor for updated_at field.
	lunchparticipantDescUpdatedAt := lunchparticipantFields[2].Descriptor()
	// lunchparticipant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	lunchparticipant.DefaultUpdatedAt = lunchparticipantDescUpdatedAt.Default.(func() time.Time)
}
