// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Lunch is the predicate function for lunch builders.
type Lunch func(*sql.Selector)

// LunchParticipant is the predicate function for lunchparticipant builders.
type LunchParticipant func(*sql.Selector)
